server:
  port: 9091
  tomcat:
    max-swallow-size: -1
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    # 数据库访问配置, 使用druid数据源 com.alibaba.druid.pool.DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&&serverTimezone=GMT%2B8
    username: ??
    password: ??
    druid:
      # 连接池配置 初始化大小、最小、最大
      initial-size: 5
      min-idle: 5
      max-active: 1000
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      # 配置日志输出
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  # Redis 配置参数
  cache:
    type: redis
  redis:
    database: 0
    host: ??
    password:
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 6000ms
      shutdown-timeout: 100ms
    timeout: 6000ms

#mybatis plus 设置
mybatis-plus:
  configuration:
    # 开启打印sql日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    default-executor-type: reuse
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  mapper-locations: classpath:com/banma/modules/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      id-type: auto
      table-prefix: zj_
      # 默认数据库表下划线命名
      table-underline: true
      # 全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-field: is_delete
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
zuji:
  # 限流数量
  limit_count: -1
  #阿里云oss存储配置
  oss:
    endpoint: ??
    outerEndpoint: ??
    accessKey: ??
    secretKey: ??
    bucketName: ??
    staticDomain: ??/
  # 微信
  wechat:
    # 网站应用
    wxWebsite:
      appId: ??
      appSecret: ??
    # 服务号/公众号
    noPublic:
      appId: ??
      appSecret: ??
    # 微信商户收款账号
    receiveAccount:
      # 证书位置
      certPath: ??
      mchId: ??
      payKey: ??
      # 支付成功回调路径
      payNotifyUrl: ??

logging:
  level:
    root: info
  file:
    path: ./logs


# 发送邮件参数
email:
  # 发送账号
  send_account: ??
  # 发送账号密码
  send_password: ??
  # 发送服务器地址
  smtp_host: smtp.exmail.qq.com
  # 发送服务器端口
  smtp_port: 465
  # 协议
  protocol: smtp
  # 收件人
  receive_mail_account: ??

